version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: willian
  MYSQL_PASSWORD: deliver@2021
  MYSQL_DATABASE: deliver
  NODE_APP_SERVER_PORT: 4000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  api:
    build: ./api
    container_name: node_server_container_api_deliver_it
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    ports:
      - 4000:4000
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: interface_container
    environment:
      <<: *common-variables
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:8080
    links:
      - server
    command: npm start